services:
  nginx:
    build: ./nginx
    ports:
      - "8081:80"
    depends_on:
      - service_1
      - service_2
    networks:
      - app-network
    volumes:
      - ./nginx/logs:/var/log/nginx

  service_1:
    build: ./service_1
    ports:
      - "8001:8001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  service_2:
    build: ./service_2
    ports:
      - "8002:8002"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge